import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import type { DiagnosticSessionDetail } from "@/lib/diagnostics-api";
import { DiagnosticSessionClient } from "../../diagnostics/[id]/session-client";
import { RouteAuditPanel } from "../../diagnostics/[id]/route-audit-panel";

const now = "2026-07-11T12:00:00.000Z";

const fixture: DiagnosticSessionDetail = {
  session: {
    id: "visual-qa-session",
    jobId: "visual-qa-job",
    equipmentId: "visual-qa-equipment",
    workflowId: "visual-qa-workflow",
    workflowVersion: 4,
    status: "testing",
    customerComplaint: "Illustrative QA fixture: unit runs but does not heat.",
    technicianObservation: "Visual QA data only; not authorized service information.",
    errorCodes: [],
    serviceTests: [],
    disposition: null,
    summary: null,
    version: 1,
    startedAt: now,
    completedAt: null,
    updatedAt: now,
  },
  equipment: {
    id: "visual-qa-equipment",
    type: "Electric range",
    make: "OpenFieldPro QA",
    model: "OFP-QA-001",
    serialNumber: "VISUAL-ONLY",
  },
  job: {
    id: "visual-qa-job",
    title: "No heat — visual verification fixture",
    status: "in_progress",
    scheduledAt: now,
  },
  workflow: {
    id: "visual-qa-workflow",
    orgId: "visual-qa-org",
    name: "Illustrative electric heat diagnostic",
    productType: "range",
    make: "OpenFieldPro QA",
    modelFamily: "OFP-QA",
    versionNumber: 4,
    supportStatus: "validated",
    lifecycleStatus: "published",
    sourceRevision: "VISUAL-QA-NOT-OEM",
    applicability: { models: ["OFP-QA-001"], notes: ["Visual regression fixture only"] },
    limitations: ["Illustrative values only. Never use as appliance service data."],
    updatedAt: now,
    createdAt: now,
  },
  measurements: [
    {
      id: "measurement-1",
      sessionId: "visual-qa-session",
      stepId: "step-supply",
      valueText: "240",
      unit: "VAC",
      result: "within_range",
      note: "Fixture reading used to verify completed-step rendering.",
      unableReason: null,
      recordedAt: now,
    },
  ],
  steps: [
    {
      id: "step-supply",
      workflowId: "visual-qa-workflow",
      stepKey: "supply",
      publicLabel: "Verify incoming supply",
      sequence: 0,
      mode: "both",
      stepType: "check",
      purpose: "Confirm both source legs before evaluating downstream controls.",
      safetyState: "Live-voltage test by a qualified technician",
      powerState: "Unit energized and calling for heat",
      operatingCondition: "Heat command active",
      meterMode: "AC volts",
      point1Label: "Terminal block L1",
      point1Endpoint: "TB-L1",
      point2Label: "Terminal block L2",
      point2Endpoint: "TB-L2",
      connector: "Terminal block",
      pin: "L1 to L2",
      wireColor: "Black to red",
      expectedText: "Illustrative 240 VAC",
      unit: "VAC",
      passInterpretation: "Continue to the controlled load path.",
      failInterpretation: "Resolve source supply before condemning an appliance component.",
      branchRules: {},
      sourceRefs: [{ fixture: true }],
      accessibilityNote: "Rear access panel removed.",
      validationStatus: "validated",
      routes: [
        {
          id: "route-supply",
          stepId: "step-supply",
          label: "L1-to-L2 source route",
          routeKind: "source_to_source",
          endpoint1: "TB-L1",
          endpoint2: "TB-L2",
          segmentIds: ["SEG-L1-01", "SEG-L1-02", "SEG-L2-01", "SEG-L2-02"],
          continuityValid: true,
          disconnectedIslands: 0,
          unintendedBranches: 0,
          visualAuditStatus: "passed",
          validationNotes: "Fixture route is intentionally complete for visual QA.",
        },
      ],
    },
    {
      id: "step-control-output",
      workflowId: "visual-qa-workflow",
      stepKey: "control-output",
      publicLabel: "Verify control output under load",
      sequence: 1,
      mode: "guided",
      stepType: "check",
      purpose: "Separate a control-output failure from an open load path.",
      safetyState: "Live-voltage test by a qualified technician",
      powerState: "Heat command active",
      operatingCondition: "Relay commanded on",
      meterMode: "AC volts",
      point1Label: "Control relay output",
      point1Endpoint: "P4-3",
      point2Label: "L2 return",
      point2Endpoint: "TB-L2",
      connector: "P4",
      pin: "3",
      wireColor: "Blue",
      expectedText: "Illustrative line voltage",
      unit: "VAC",
      passInterpretation: "Continue to load resistance and harness continuity.",
      failInterpretation: "Verify relay input and command state before any control recommendation.",
      branchRules: {},
      sourceRefs: [{ fixture: true }],
      accessibilityNote: "Back-probe only at the published connector point.",
      validationStatus: "validated",
      routes: [
        {
          id: "route-control-output",
          stepId: "step-control-output",
          label: "Controlled L1 path to load",
          routeKind: "source_to_load",
          endpoint1: "P4-3",
          endpoint2: "LOAD-H1",
          segmentIds: ["SEG-CTL-01", "SEG-CTL-02", "SEG-HARNESS-07"],
          continuityValid: true,
          disconnectedIslands: 0,
          unintendedBranches: 0,
          visualAuditStatus: "passed",
          validationNotes: "Ordered segment IDs must remain visible in screenshots.",
        },
      ],
    },
    {
      id: "step-load",
      workflowId: "visual-qa-workflow",
      stepKey: "load-resistance",
      publicLabel: "Verify heater continuity",
      sequence: 2,
      mode: "field",
      stepType: "check",
      purpose: "Confirm the load is electrically continuous with power removed.",
      safetyState: "Power disconnected; verify zero volts before resistance testing",
      powerState: "Unit unplugged",
      operatingCondition: "Harness isolated from the load",
      meterMode: "Ohms",
      point1Label: "Heater terminal H1",
      point1Endpoint: "LOAD-H1",
      point2Label: "Heater terminal H2",
      point2Endpoint: "LOAD-H2",
      connector: "Heater terminals",
      pin: "H1 to H2",
      wireColor: "Blue to red",
      expectedText: "Illustrative continuity range",
      unit: "Ω",
      passInterpretation: "Load is continuous; return to the energized path checks.",
      failInterpretation: "Document the open load before preparing a repair recommendation.",
      branchRules: {},
      sourceRefs: [{ fixture: true }],
      accessibilityNote: "Disconnect at least one conductor before measuring.",
      validationStatus: "pilot",
      routes: [
        {
          id: "route-load",
          stepId: "step-load",
          label: "Across-load continuity path",
          routeKind: "across_load",
          endpoint1: "LOAD-H1",
          endpoint2: "LOAD-H2",
          segmentIds: ["SEG-LOAD-01", "SEG-LOAD-02"],
          continuityValid: true,
          disconnectedIslands: 0,
          unintendedBranches: 1,
          visualAuditStatus: "pending",
          validationNotes: "Deliberate review-required state verifies warning presentation.",
        },
      ],
    },
  ],
};

export default function DiagnosticVisualQaPage() {
  if (process.env.OFP_VISUAL_QA !== "1") notFound();

  return (
    <div>
      <PageHeader
        title="OpenFieldPro diagnostic visual QA"
        description="Deterministic fixture — illustrative values only, never service data"
      />
      <DiagnosticSessionClient initialDetail={fixture} />
      <RouteAuditPanel steps={fixture.steps} />
    </div>
  );
}
